/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package swagger.api;

import swagger.model.ErrorResponse;
import swagger.model.HIUSubscriptionNotificationAcknowledgment;
import swagger.model.HIUSubscriptionRequestNotificationAcknowledgement;
import swagger.model.HeartbeatResponse;
import swagger.model.SubscriptionRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-08-22T15:53:53.899420813Z[GMT]")
@Validated
public interface V05Api {

    @Operation(summary = "Response to patient's account discovery request", description = "Result of patient care-context discovery request at HIP end. If a matching patient found with zero or more care contexts associated, it is specified as result attribute. If the prior discovery request, resulted in errors then it is specified in the error attribute. Reasons of errors can be    1. **more than one definitive match for the given request**    2. **no verified identifer was specified** ", tags={ "discovery" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Format mismatch of any of attributes. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/care-contexts/on-discover",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05CareContextsOnDiscoverPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientDiscoveryResult body);


    @Operation(summary = "Create consent request", description = "Creates a consent request to get data about a patient by HIU user. CM should call Gateway - ***_/v0.5/consent-requests/on-init*** API with the consent-request-id", tags={ "consent" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Invalid data sent    * Required attributes not mentioned ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Expired/Invalid token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/consent-requests/init",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05ConsentRequestsInitPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConsentRequest body);


    @Operation(summary = "Get consent request status", description = "Get status of consent request done previously. CM responds by calling Gateway API - ***_/v0.5/consent-requests/on-status***", tags={ "consent" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Invalid data sent ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Expired/Invalid token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/consent-requests/status",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05ConsentRequestsStatusPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConsentRequestStatusRequest body);


    @Operation(summary = "Get consent artefact", description = "This API is called when a HIU makes a request to get a consent artefact. For response please refer to the Gateway ***_/v0.5/consents/on-fetch***", tags={ "consent" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Invalid data sent ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Expired/Invalid token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/consents/fetch",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05ConsentsFetchPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ConsentFetchRequest body);


    @Operation(summary = "Consent notification", description = "This API is called by HIP as acknowledgement to notification of consents, in cases of consent revocation and expiration, notified by CM earlier via Gateway API - ***_/v0.5/consents/hip/notify***. ", tags={ "consent" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Invalid/Expired/Empty token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream services are down ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/consents/hip/on-notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05ConsentsHipOnNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HIPConsentNotificationResponse body);


    @Operation(summary = "Consent notification", description = "This API is called by HIU as acknowledgement to consent notifications, specifically for cases when consent is REVOKED or EXPIRED, notified by CM earlier via Gateway API - ***_/v0.5/consents/hiu/notify***. ", tags={ "consent" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted."),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Invalid/Expired/Empty token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream services are down ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/consents/hiu/on-notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05ConsentsHiuOnNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HIUConsentNotificationResponse body);


    @Operation(summary = "Notifications corresponding to events during data flow", description = "API called by HIU and HIP during data-transfer.  1. HIP on transfer of data would send **sessionStatus** - one of [TRANSFERRED, FAILED] 2. HIP would also send **hiStatus** for each *careContextReference* - on of [DELIVERED, ERRORED] 3. HIU on receipt of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]. For example, FAILED when if data was not sent or if invalid data was sent 4. HIU would also send **hiStatus** for each *careContextReference* - one of [OK, ERRORED] ", tags={ "data flow" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Notification is Accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Invalid Request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Expired/Invalid token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/health-information/notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05HealthInformationNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HealthInformationNotification body);


    @Operation(summary = "Health information data request acknowledgement from HIP", description = "This API is called by HIP to acknowledge Health information request receipt. When HIU requests health information, CM generates a transactionId and makes a health information request to the HIP(s). HIPs acknowledgement to the health-information request is coveyed by this API. Either the **hiRequest** or **error** must be specified. **hiRequest** element returns the same transactionId as before with a status indicating that the request is acknowledged. ", tags={ "data flow" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted."),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Bad request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Token is invalid or Link has expired ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/health-information/on-request",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05HealthInformationOnRequestPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HIPHealthInformationRequestAcknowledgement body);


    @Operation(summary = "Health information data request from HIU", description = "HIU request for Health information against a consent id. CM would generate a transactionId against each consent and pass it as trnasaction context / correlation id to the HIP and also return the same to HIU via Gateway API - ***_/v0.5/health-information/cm/on-request***. ", tags={ "data flow" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Bad request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Token is invalid or Link has expired ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/health-information/request",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05HealthInformationRequestPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HIRequest body);


    @Operation(summary = "Informs about server status", description = "", tags={ "monitoring" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = HeartbeatResponse.class))) })
    @RequestMapping(value = "/v0.5/heartbeat",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<HeartbeatResponse> v05HeartbeatGet();


    @Operation(summary = "This API is meant to be called by HIPs when there is new health data generated for a patient, against a care context that is already linked to patient's NDHM account.", description = "This API is called by HIP only when there is new health data is added/created for a patient and under a care context that is already linked with patient's Health Account.  HIP can send following things in this API to notify the Consent Manager about the new health data added:   1. **Patient's Identifier for which the new health data is added (It can be NDHM id or NDHM number)**   2. **Care Context reference under which the new health data is added**   3. **Patient's reference (An identifier with which the patient is registered on HIP)**   4. **Types of health information documents that have been added**   5. **A date when the health information was created/added on the HIP** Note: This API shouldn't be called if the new heath data of is added/created under new care context. ", tags={ "hip facing", "link" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "accepted"),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/links/context/notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05LinksContextNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HipDataNotificationRequest body);


    @Operation(summary = "API for HIP initiated care-context linking for patient", description = "API to submit care-context to CM for HIP initiated linking. The API must accompany the \"accessToken\" fetched in the users/auth process.     1. subsequent usage for accessToken may be invalid if it was meant for one-time usage or if it expired ", tags={ "link" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * required information not provided ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/links/link/add-contexts",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05LinksLinkAddContextsPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientCareContextLinkRequest body);


    @Operation(summary = "Token authenticated by HIP, indicating completion of linkage of care-contexts", description = "Returns a list of linked care contexts with patient reference number.   1. **Validated and linked account reference number**   2. **Validated that the token sent from Consent Manager is same as the one generated by HIP**   3. **Verified that same Consent Manager which made the link request is sending the token**   4. **Results of unmasked linked care contexts with patient reference number** ", tags={ "link" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * resp not specified   * atleast patient or error should be specified ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/links/link/on-confirm",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05LinksLinkOnConfirmPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientLinkResult body);


    @Operation(summary = "Response to patient's care context link request", description = "Result of patient care-context link request from HIP end. This happens in context of previous discovery of patient found at HIP end, therefore the link requests ought to be in reference to the patient reference and care-context references previously returned by the HIP. The correlation of discovery and link request is maintained through the transactionId. HIP should have   1. **Validated transactionId in the request to check whether there was a discovery done previously, and the link request corresponds to returned patient care care context references**   2. **Before returning the response, HIP should have sent an authentication request to the patient(eg: OTP verification)**   3. **HIP should communicate the mode of authentication of a successful request**   4. **HIP subsequently should expect the token passed via /link/confirm against the link.referenceNumber passed in this call**    The error section in the body, represents the potential errors that may have occurred. Possible reasons:   1. **Patient reference number is invalid**   2. **Care context reference numbers are invalid** ", tags={ "link" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Format mismatch of any of attributes. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/links/link/on-init",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05LinksLinkOnInitPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientLinkReferenceResult body);


    @Operation(summary = "Identify a patient by her consent-manager user-id", description = "This API is meant for identify to patient given her consent-manager-user-id. CM subsequently makes the /on-find Gateway API call with results. ", tags={ "identification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "Invalid request, required attributes not provided ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/patients/find",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05PatientsFindPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientIdentificationRequest body);


    @Operation(summary = "Response to patient's share profile request", description = "Result of patient share profile request at HIP end. ", tags={ "profile" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Format mismatch of any of attributes. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/patients/profile/on-share",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05PatientsProfileOnSharePost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody ShareProfileResult body);


    @Operation(summary = "Acknowledgment by Gateway", description = "This API is to check if the Status is successfully sent for patient (Active/Deactivate)  then \"status\" will be \"OK\" with no error. ", tags={ "hip facing", "patient notification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/patients/status/on-notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05PatientsStatusOnNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientStatusNotification body);


    @Operation(summary = "Request for subscription", description = "creates a request for subscription. The subscription categories can be for care-contexts linkages or availability of data against existing care-contexts. Note that the requester must have HIU role", tags={ "subscriptions" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * Invalid data sent    * Required attributes not mentioned ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Expired/Invalid token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/subscription-requests/cm/init",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05SubscriptionRequestsCmInitPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody SubscriptionRequest body);


    @Operation(summary = "Callback API for /subscription-requests/hiu/notify to acknowledge receipt of notification.", description = "This API is called by HIU as acknowledgement to subscription request relevant notifications. ", tags={ "subscriptions" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted."),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Invalid/Expired/Empty token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream services are down ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/subscription-requests/hiu/on-notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05SubscriptionRequestsHiuOnNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HIUSubscriptionRequestNotificationAcknowledgement body);


    @Operation(summary = "Callback API for /subscriptions/hiu/notify to acknowledge receipt of notification.", description = "This API is called by HIU as acknowledgement to consent notifications, specifically for cases when consent is REVOKED or EXPIRED. ", tags={ "subscriptions", "hiu facing" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted."),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Invalid/Expired/Empty token. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream services are down ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/subscriptions/hiu/on-notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05SubscriptionsHiuOnNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody HIUSubscriptionNotificationAcknowledgment body);


    @Operation(summary = "Confirmation request sending token, otp or other authentication details from HIP/HIU for confirmation", description = "This API is called by HIP/HIUs to confirm authentication of users. The transactionId returned by the previous callback API /users/auth/on-init must be sent. If Authentication is successful the callback API will send an \"access token\" for subsequent purpose specific API calls. Note only **credential.authCode** or **credential.demographic** should be sent   1. demographic details are only required for  demographic auth as of now.    2. demographic details are required only in MEDIATED cases and if the **auth.mode** so demands. e.g. if **auth.mode** is DEMOGRAPHICS. Usually for demographic authentication, the name, gender and DOB must be exactly as specified in User Account.   3. demographic.identifier is optional, however maybe required if authentication so mandates.    4. credential.authCode is required for other MEDIATED authentication like MOBILE_OTP, AADHAAR_OTP. ", tags={ "user auth" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * transaction id is not provided or invalid   * token or other auth confirmation details not provided or invalid ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/users/auth/confirm",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05UsersAuthConfirmPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientAuthConfirmRequest body);


    @Operation(summary = "Get a patient's authentication modes relevant to specified purpose", description = "This API is meant for identify supported authentication modes for a patient given a specific purpose ", tags={ "user auth", "hip facing" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request Accepted"),
        
        @ApiResponse(responseCode = "400", description = "Invalid request, required attributes not provided ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/users/auth/fetch-modes",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05UsersAuthFetchModesPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientAuthModeQueryRequest body);


    @Operation(summary = "Initialize authentication from HIP", description = "This API is called by HIPs to initiate authentication of users. A transactionId is retuned by the corresponding callback API for confirmation of user auth. ", tags={ "user auth" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * patient id is not provided ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/users/auth/init",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05UsersAuthInitPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientAuthInitRequest body);


    @Operation(summary = "callback API from HIU/HIPs as acknowledgement of auth notification (in case of DIRECT auth)", description = "This API is called by HIU/HIPs to confirm acknowledgement for receipt of auth notification is case of DIRECT authentication. ", tags={ "user auth", "hip facing", "hiu facing" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Request accepted"),
        
        @ApiResponse(responseCode = "400", description = "**Causes:**   * required details not provided   * neither auth nor error specified ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "**Causes:**   * Unauthorized request ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))),
        
        @ApiResponse(responseCode = "500", description = "**Causes:**   * Downstream system(s) is down.   * Unhandled exceptions. ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))) })
    @RequestMapping(value = "/v0.5/users/auth/on-notify",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> v05UsersAuthOnNotifyPost(@Parameter(in = ParameterIn.HEADER, description = "Access token which was issued after successful login with gateway auth server." ,required=true,schema=@Schema()) @RequestHeader(value="Authorization", required=true) String authorization, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody PatientAuthNotificationAcknowledgement body);

}

